In [1]:
import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier

In [2]:
df = pd.read_csv('train.csv')

In [4]:
df_y = df['class']
df_x = df.drop('class', axis = 1)

In [35]:
clf_euc = KNeighborsClassifier(3, p=2)
clf_euc.fit(df_x, df_y)
df_x


x         y         z
0    8.599291  9.729418  6.432371
1    6.592955  0.082556  1.969544
2    5.596471  9.815682  0.027295
3    2.743639  8.783177  4.041946
4    4.458362  5.750222  0.099070
..        ...       ...       ...
995  4.617314  7.700236  5.907128
996  5.453472  1.798360  1.992616
997  2.553853  8.122934  3.970146
998  3.210456  3.342092  7.831479
999  6.930237  2.742352  4.678527

[1000 rows x 3 columns]

In [36]:
clf_euc.score(df_x, df_y)

/home/eashan/.local/lib/python3.8/site-packages/sklearn/neighbors/_classification.py:237: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


0.951

In [37]:
test_df = pd.read_csv('test.csv')
tdf_y = test_df['actual-class']
tdf_x = test_df.drop('actual-class', axis = 1)
tdf_x = tdf_x.drop('ID', axis = 1)
tdf_x

x         y         z
0   8.074807  5.988044  3.844979
1   4.952249  5.823205  1.612045
2   4.773178  0.078757  4.209442
3   9.845919  2.055448  3.525702
4   1.612492  1.320515  8.200455
5   7.987555  9.188111  7.222228
6   0.311558  3.974680  7.897371
7   1.219113  0.266045  2.741136
8   0.636340  1.831257  6.767459
9   0.890168  8.613714  2.884227
10  7.226514  9.852794  7.373560
11  2.709551  3.719191  5.743540
12  2.842368  1.902145  2.216614
13  3.610773  4.589548  7.714008
14  4.888200  6.720637  7.261562
15  8.857224  9.056900  8.862604
16  8.239402  9.347802  5.277351
17  3.219759  2.980960  6.646886
18  2.146974  5.328725  5.801703
19  1.156302  8.542813  1.859447

In [38]:
clf_euc.score(tdf_x, tdf_y)

/home/eashan/.local/lib/python3.8/site-packages/sklearn/neighbors/_classification.py:237: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


0.95

In [79]:
print(clf_euc.predict_proba([[6.930237, 2.742352, 4.678527]]))
print(clf_euc.predict_proba([[1.156302, 8.542813, 1.859447]]))
print(clf_euc.predict_proba(tdf_x))

[[0.33333333 0.66666667]]
[[1. 0.]]
[[0.         1.        ]
 [0.66666667 0.33333333]
 [1.         0.        ]
 [0.         1.        ]
 [1.         0.        ]
 [0.         1.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [0.         1.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [0.33333333 0.66666667]
 [0.         1.        ]
 [0.         1.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]]


/home/eashan/.local/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(
/home/eashan/.local/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


In [78]:
clf_manh = KNeighborsClassifier(3, p=1)
clf_manh.fit(df_x, df_y)
print(clf_manh.score(df_x, df_y))
print(clf_manh.score(tdf_x, tdf_y))
print(clf_manh.predict_proba([[6.930237, 2.742352, 4.678527]]))
print(clf_manh.predict_proba([[1.156302, 8.542813, 1.859447]]))
print(clf_manh.predict_proba(tdf_x))


0.948
1.0
[[0.33333333 0.66666667]]
[[1. 0.]]
[[0.         1.        ]
 [0.66666667 0.33333333]
 [1.         0.        ]
 [0.         1.        ]
 [1.         0.        ]
 [0.         1.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [0.         1.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [0.66666667 0.33333333]
 [0.         1.        ]
 [0.         1.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]]


/home/eashan/.local/lib/python3.8/site-packages/sklearn/neighbors/_classification.py:237: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)
/home/eashan/.local/lib/python3.8/site-packages/sklearn/neighbors/_classification.py:237: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Se

In [77]:
clf_euc.predict(tdf_x)

/home/eashan/.local/lib/python3.8/site-packages/sklearn/neighbors/_classification.py:237: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


array([1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0])

In [74]:
clf_manh.predict(tdf_x)

/home/eashan/.local/lib/python3.8/site-packages/sklearn/neighbors/_classification.py:237: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


array([1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0])

In [75]:
tdf_y

0     1
1     0
2     0
3     1
4     0
5     1
6     0
7     0
8     0
9     0
10    1
11    0
12    0
13    0
14    0
15    1
16    1
17    0
18    0
19    0
Name: actual-class, dtype: int64

In [ ]:
#so the prediction is 100% accurate 
#    Euclidean knn       Manhattan knn
#        actual              actual
#          +  -               +  -
#  pred + 6   0             + 6  0
#       - 1  13             - 0  14
# 
#  Accuracy = 0.95        Accuracy = 1
#  precision = 1          precision = 1
#  recall = 0.857           recall = 1
#  F-measure = 0.923      F-measure = 1
#
# The manhattan method gives better perfermance.

