In [8]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier

In [9]:
data = pd.read_csv("iris.data")
data.columns = ["sep-len","sep-wid","ped-len","ped-wid","class"]

In [10]:
x_train, x_test, y_train, y_test = train_test_split(data.iloc[:, 0:4].values,data.iloc[:, 4].values, test_size = 0.2, random_state=0)

In [11]:
standard = StandardScaler()
x_train = standard.fit_transform(x_train)
x_test = standard.transform(x_test)
x_test

array([[ 0.26802248, -1.06783371,  1.00315453,  0.20056536],
       [ 0.76251356,  0.30344915,  0.71770405,  0.98739871],
       [-1.09182799, -2.43911656, -0.19573747, -0.3239902 ],
       [-0.47371414, -1.52492799, -0.08155728, -0.3239902 ],
       [-1.83356461, -0.38219228, -1.39462947, -1.37310134],
       [ 2.12236402, -0.15364514,  1.57405548,  1.11853761],
       [ 1.25700463,  0.074902  ,  0.71770405,  1.38081539],
       [-0.2264686 , -0.38219228,  0.2038932 ,  0.06942647],
       [ 0.14439971, -1.98202227,  0.66061396,  0.33170426],
       [ 0.14439971,  0.76054343,  0.37516348,  0.46284315],
       [-1.21545076,  0.074902  , -1.33753937, -1.50424023],
       [-1.33907353, -0.15364514, -1.39462947, -1.24196244],
       [-0.2264686 , -0.61073942,  0.37516348,  0.06942647],
       [-1.09182799, -0.15364514, -1.28044928, -1.37310134],
       [-1.83356461, -0.15364514, -1.45171956, -1.37310134],
       [ 0.51526802, -0.61073942,  0.71770405,  0.33170426],
       [ 1.13338186, -0.

In [6]:
analysis = LinearDiscriminantAnalysis()
x_train = analysis.fit_transform(x_train,y_train)
x_test = analysis.transform(x_test)

In [12]:
classifier = RandomForestClassifier(random_state=0)

classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)

In [14]:
print(accuracy_score(y_test, y_pred))

#Since the accurace score is quite high I think the results of the LDA was good.

0.9


In [22]:
cancer_data = pd.read_csv("wdbc.data")
cancer_data.columns = ["ID_Number", "Diagnosis","Features","Features","Features","Features","Features","Features","Features","Features","Features","Features","Features","Features","Features","Features","Features","Features","Features","Features","Features","Features","Features","Features","Features","Features","Features","Features","Features","Features","Features","Features"]
cancer_features = cancer_data["Features"]
cancer_Diagnosis = cancer_data["Diagnosis"]

In [24]:
x_test_cancer = cancer_features[:114]
x_train_cancer = cancer_features[114:]
y_test_cancer = cancer_Diagnosis[:114]
y_train_cancer = cancer_Diagnosis[114:]





Features  Features  Features  Features  Features  Features  Features  \
114     11.93     21.53     76.53     438.6   0.09768   0.07849   0.03328   
115      8.95     15.76     58.74     245.2   0.09462   0.12430   0.09263   
116     14.87     16.67     98.64     682.5   0.11620   0.16490   0.16900   
117     15.78     22.91    105.70     782.6   0.11550   0.17520   0.21330   
118     17.95     20.01    114.20     982.0   0.08402   0.06722   0.07293   
..        ...       ...       ...       ...       ...       ...       ...   
563     21.56     22.39    142.00    1479.0   0.11100   0.11590   0.24390   
564     20.13     28.25    131.20    1261.0   0.09780   0.10340   0.14400   
565     16.60     28.08    108.30     858.1   0.08455   0.10230   0.09251   
566     20.60     29.33    140.10    1265.0   0.11780   0.27700   0.35140   
567      7.76     24.54     47.92     181.0   0.05263   0.04362   0.00000   

     Features  Features  Features  ...  Features  Features  Features  \
114   0.02008    0.1688   0.06194  ...    13.670     26.15     87.54   
115   0.02308    0.1305   0.07163  ...     9.414     17.07     63.34   
116   0.08923    0.2157   0.06768  ...    18.810     27.37    127.10   
117   0.09479    0.2096   0.07331  ...    20.190     30.50    130.30   
118   0.05596    0.2129   0.05025  ...    20.580     27.83    129.20   
..        ...       ...       ...  ...       ...       ...       ...   
563   0.13890    0.1726   0.05623  ...    25.450     26.40    166.10   
564   0.09791    0.1752   0.05533  ...    23.690     38.25    155.00   
565   0.05302    0.1590   0.05648  ...    18.980     34.12    126.70   
566   0.15200    0.2397   0.07016  ...    25.740     39.42    184.60   
567   0.00000    0.1587   0.05884  ...     9.456     30.37     59.16   

     Features  Features  Features  Features  Features  Features  Features  
114     583.0   0.15000   0.23990    0.1503   0.07247    0.2438   0.08541  
115     270.0   0.11790   0.18790    0.1544   0.03846    0.1652   0.07722  
116    1095.0   0.18780   0.44800    0.4704   0.20270    0.3585   0.10650  
117    1272.0   0.18550   0.49250    0.7356   0.20340    0.3274   0.12520  
118    1261.0   0.10720   0.12020    0.2249   0.11850    0.4882   0.06111  
..        ...       ...       ...       ...       ...       ...       ...  
563    2027.0   0.14100   0.21130    0.4107   0.22160    0.2060   0.07115  
564    1731.0   0.11660   0.19220    0.3215   0.16280    0.2572   0.06637  
565    1124.0   0.11390   0.30940    0.3403   0.14180    0.2218   0.07820  
566    1821.0   0.16500   0.86810    0.9387   0.26500    0.4087   0.12400  
567     268.6   0.08996   0.06444    0.0000   0.00000    0.2871   0.07039  

[454 rows x 30 columns]

In [89]:
#idk how to get this to work :( lol )

def predict(row, coefficients):
    yhat = coefficients[0]
    
    print(coefficients[0+1], row[0])
    for i in range(len(row)-1):
        yhat += coefficients[i + 1] * row[i+1]
    return yhat



def coefficients_sgd(train, l_rate, n_epoch):
    print("test",len(train[0]))
    coef = [0.0 for i in range(len(train[0]))]
    for epoch in range(n_epoch):
        print(train)
        for row in train:
            yhat = predict(row, coef)
            error = yhat - row[-1]
            coef[0] = coef[0] - l_rate * error
            for i in range(len(row)-1):
                coef[i + 1] = coef[i + 1] - l_rate * error * row[i]
            # print(l_rate, n_epoch, error)
    return coef
 

def linear_regression_sgd(train, test, l_rate, n_epoch):
    train = train.to_numpy()
    train = train[1: , :]
    predictions = list()
    coef = coefficients_sgd(train, l_rate, n_epoch)
    for row in test:
        yhat = predict(row, coef)
    predictions.append(yhat)
    return(predictions)



In [90]:
# kinda works maybe

linear_regression_sgd(x_train_cancer, x_test_cancer, 0.01, 50)

test 30
[[8.950e+00 1.576e+01 5.874e+01 ... 3.846e-02 1.652e-01 7.722e-02]
 [1.487e+01 1.667e+01 9.864e+01 ... 2.027e-01 3.585e-01 1.065e-01]
 [1.578e+01 2.291e+01 1.057e+02 ... 2.034e-01 3.274e-01 1.252e-01]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]
0.0 8.95
0.006911189999999999 14.87
-13.044166584141532 15.78
33982.25175814916 17.95
-106632120.14584766 11.41
78964045264.88005 18.66
-275085382518529.4 24.25
1.8767302308986936e+18 14.5
-2.7710991644905586e+21 13.37
3.0714534263184513e+24 13.85
-3.8756395982471125e+27 13.61
5.367451978513613e+30 19.0
-2.122231771643165e+34 15.1
3.4071124856851115e+37 19.79
-1.3084297005464844e+41 12.19
1.180463445109261e+44 15.46
-2.5327066907913934e+47 16.16
6.242128324821694e+50 15.71
-1.2573464137868872e+54 18.45
4.385744358802456e+57 12.77
-4.921462259785791e+60 11.71
4.0684747445876355e

/tmp/ipykernel_5430/2840560509.py:6: RuntimeWarning: overflow encountered in double_scalars
  yhat += coefficients[i + 1] * row[i+1]
/tmp/ipykernel_5430/2840560509.py:19: RuntimeWarning: invalid value encountered in double_scalars
  coef[0] = coef[0] - l_rate * error
/tmp/ipykernel_5430/2840560509.py:21: RuntimeWarning: invalid value encountered in double_scalars
  coef[i + 1] = coef[i + 1] - l_rate * error * row[i]


nan 12.07
nan 11.75
nan 11.67
nan 13.68
nan 20.47
nan 10.96
nan 20.55
nan 14.27
nan 11.69
nan 7.729
nan 7.691
nan 11.54
nan 14.47
nan 14.74
nan 13.21
nan 13.87
nan 13.62
nan 10.32
nan 10.26
nan 9.683
nan 10.82
nan 10.86
nan 11.13
nan 12.77
nan 9.333
nan 12.88
nan 10.29
nan 10.16
nan 9.423
nan 14.59
nan 11.51
nan 14.05
nan 11.2
nan 15.22
nan 20.92
nan 21.56
nan 20.13
nan 16.6
nan 20.6
nan 7.76
[[8.950e+00 1.576e+01 5.874e+01 ... 3.846e-02 1.652e-01 7.722e-02]
 [1.487e+01 1.667e+01 9.864e+01 ... 2.027e-01 3.585e-01 1.065e-01]
 [1.578e+01 2.291e+01 1.057e+02 ... 2.034e-01 3.274e-01 1.252e-01]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]
nan 8.95
nan 14.87
nan 15.78
nan 17.95
nan 11.41
nan 18.66
nan 24.25
nan 14.5
nan 13.37
nan 13.85
nan 13.61
nan 19.0
nan 15.1
nan 19.79
nan 12.19
nan 15.46
nan 16.16
nan 15.71
nan 18.45
nan 12.77


TypeError: can't multiply sequence by non-int of type 'numpy.float64'

In [ ]:
#this should be correct tho

def accuracy(y_act, y_pred):

    tp = sum((y_act == 1) & (y_pred == 1))
    tn = sum((y_act == 0) & (y_pred == 0))
    fn = sum((y_act == 1) & (y_pred == 0))
    fp = sum((y_act == 0) & (y_pred == 1))
    
    return ((tp + tn) * 100)/ float( tp + tn + fn + fp)



def precision(y_act, y_pred):

    tp = sum((y_act == 1) & (y_pred == 1))
    tn = sum((y_act == 0) & (y_pred == 0))
    fn = sum((y_act == 1) & (y_pred == 0))
    fp = sum((y_act == 0) & (y_pred == 1))
    
    return (tp  * 100)/ float( tp + fp)




def recall(y_act, y_pred):
    tp = sum((y_act == 1) & (y_pred == 1))
    tn = sum((y_act == 0) & (y_pred == 0))
    fn = sum((y_act == 1) & (y_pred == 0))
    fp = sum((y_act == 0) & (y_pred == 1))
    return (tp  * 100)/ float( tp + fn)

